server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_judge
    username: root
    password: mo
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml