server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_judge
    username: root
    password: mo
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost           # Redis服务器地址
    database: 0               # Redis数据库索引（默认为0）
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    timeout: 1000ms         # 连接超时时间
    lettuce:          #配置连接
      pool:
        max-active: 8       #连接池最大连接数
        max-idle: 8         #连接池最大空闲数
        min-idle: 0         #连接词最小空闲连接数
        max-wait: -1ms      #连接池最大阻塞等待实践，负值表示没有限制
#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: [classpath:/]

mybatis:
  mapper-locations: classpath:mapper/*.xml